// Wire formats for the two kinds of Freizone QR codes:
//
// `freizone://join` carries a server address and (when the policy needs
// one) an invite code, so a scanning device can join that server --
// generated by invite_screen.dart, consumed by the setup wizard's scanner
// (qr_scan_screen.dart). See docs/PROTOCOL.md's "Invite QR codes" appendix
// in freizone-server.
//
// `freizone://chat` carries an already-registered account's own address
// (id + server, both required) plus an optional display-name suggestion,
// so a scanning device can jump straight to starting a conversation with
// that account instead of typing the address by hand. Unlike the join
// invite's one-time code, this carries no secret or capability -- an
// account's id*server address is already public information (resolvable
// via the server's own public GET /v1/accounts/{id}), so there's no
// expiry/revocation to model, just a convenience encoding of it. See
// docs/PROTOCOL.md's "Chat invite QR codes" appendix.
//
// Both builders strip a redundant default "https://" from the server
// they encode (via withoutDefaultScheme) -- an https server address
// otherwise reads oddly next to an id, unlike how nobody writes the
// scheme in front of an email address. A non-default scheme (plain
// "http://", for a local/dev/test server) stays visible, since that's
// the one case actually worth flagging. The parse side needs no
// matching change: whatever ends up in _serverController/_idController
// downstream already runs through normalizeServerUrl (setup_screen.dart)
// or parseFreizoneAddress (AppSession.startConversation), both of which
// already add "https://" back when a server string has no scheme.
import 'package:flutter/foundation.dart';

import 'freizone_address.dart';

@immutable
class InviteUri {
  const InviteUri({required this.server, this.code});

  final String server;
  final String? code;
}

Uri buildInviteUri({required String server, String? code}) {
  return Uri(
    scheme: 'freizone',
    host: 'join',
    queryParameters: {
      'server': withoutDefaultScheme(server),
      if (code != null && code.isNotEmpty) 'code': code,
    },
  );
}

/// Returns null if raw isn't a recognizable `freizone://join` invite URI.
InviteUri? parseInviteUri(String raw) {
  final uri = Uri.tryParse(raw.trim());
  if (uri == null || uri.scheme != 'freizone' || uri.host != 'join')
    return null;
  final server = uri.queryParameters['server'];
  if (server == null || server.isEmpty) return null;
  final code = uri.queryParameters['code'];
  return InviteUri(
    server: server,
    code: (code == null || code.isEmpty) ? null : code,
  );
}

@immutable
class ChatInviteUri {
  const ChatInviteUri({required this.id, required this.server, this.name});

  final String id;
  final String server;
  final String? name;
}

Uri buildChatInviteUri({
  required String id,
  required String server,
  String? name,
}) {
  return Uri(
    scheme: 'freizone',
    host: 'chat',
    queryParameters: {
      'id': id,
      'server': withoutDefaultScheme(server),
      if (name != null && name.isNotEmpty) 'name': name,
    },
  );
}

/// Returns null if raw isn't a recognizable `freizone://chat` invite URI.
ChatInviteUri? parseChatInviteUri(String raw) {
  final uri = Uri.tryParse(raw.trim());
  if (uri == null || uri.scheme != 'freizone' || uri.host != 'chat')
    return null;
  final id = uri.queryParameters['id'];
  final server = uri.queryParameters['server'];
  if (id == null || id.isEmpty || server == null || server.isEmpty)
    return null;
  final name = uri.queryParameters['name'];
  return ChatInviteUri(
    id: id,
    server: server,
    name: (name == null || name.isEmpty) ? null : name,
  );
}
